import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Container, Theme } from "@radix-ui/themes";
import Navbar from "./Navbar";
import AuthProvider from "./auth/Provider";
import QueryReactProvider from "./QueryReactProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <QueryReactProvider>
          <AuthProvider>
            <Theme accentColor="violet">
              <Navbar />
              <Container>
                <main className="p-5">{children}</main>
              </Container>
            </Theme>
          </AuthProvider>
        </QueryReactProvider>
      </body>
    </html>
  );
}
